version: '3.7'

services:
  app:
    build: .
    command: python /usr/src/app/recipebook/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user_django
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=django_dev
volumes:
  postgres_data: