# Generated by Django 3.2.8 on 2021-10-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50, verbose_name='Название')),
                ('type_product', models.CharField(default=None, max_length=50, verbose_name=' Вид')),
            ],
            options={
                'verbose_name': 'Игредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('time_cook', models.IntegerField(default=None, verbose_name='Время приготовления (мин.)')),
                ('ingredients', models.ManyToManyField(related_name='recipe_ingredients', to='main.Ingredient', verbose_name='Ингридиенты')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
